### PR TITLE
Fix configuration loading

### LINKED ISSUE #385: Cannot load the configuration file
Jangouts supports a few configuration options using a `config.json` file which is retrieved at runtime. This mechanism does not work in the `react-redux` branch.

### PR DESCRIPTION
**Pull request by imobachgs**
Fixes #385. By the way, I took the opportunity to simplify the code by using the [Fetch API](https://developer.mozilla.org/es/docs/Web/API/Fetch_API).

### CODE REVIEW

File: src/utils/config.js [hunk 1]
```diff
@@ -50,63 +50,43 @@ const defaultJanusServer = () => {
...
 
-const READY_STATE_DONE = 4;
-const STATUS_SUCCESS = 200;
-
 /**
- * Fetches and parses the configuration from the `config.json` file.
+ * Retrieves the configuration
  *
- * @returns {Object}
+ * It tries to get a custom configuration from `/config.json`. If a valid configuration
```
Comment (dgdavid) [inline src/utils/config.js:79]: For other readers: example available in https://github.com/jangouts/jangouts/blob/215b1b107d332ea0108869213755dd8573cd7c98/public/config.json.sample

**Review by dgdavid — APPROVED** [review]
LGTM :+1:
