### PR TITLE
Stop tracks when disconnecting (fixes ##394)

### LINKED ISSUE #394: When quiting a room, the camera remains activated
If you use the icon "Leave the room", you end up in the login form... but with the camera still on.

### PR DESCRIPTION
**Pull request by ancorgs**
When leaving the room, stop all the tracks so the browser is aware of the disconnection and turns off the physical indicators (like the camera light).

Fixes #394

### CODE REVIEW

**Comment by ancorgs** [comment]
Not adding a unit test because the only one I can come with would be all mocking and basically reproducing the implementation.

**Review by imobachgs — APPROVED** [review]

File: src/janus-api/models/feed.ts [hunk 1]
```diff
@@ -224,6 +224,19 @@ export class Feed {
...
+    this.removeStream();
+  };
+
+  /**
+   * Unsets the stream from the feed, stopping all its tracks.
+   */
+  private removeStream() {
+    if (this.stream) {
+      let tracks = this.stream.getTracks();
+      for(let i in tracks) {
```
Comment (joseivanlopez) [inline src/janus-api/models/feed.ts:236]: Maybe this also works:

~~~
tracks.map(t => t.stop());
~~~

Comment (imobachgs) [reply src/janus-api/models/feed.ts:236]: I would use `forEach` because you are not "mapping" at all.

Comment (joseivanlopez) [reply src/janus-api/models/feed.ts:236]: ah, right. I  only wanted to point that we can "functionally" iterate.
